### ISSUE TITLE
"URLError:Connection reset by peer" when trying to retrieve last 560 days' worth of transactions

### ISSUE THREAD

**Issue by parxier** [ArtS/nab-export#1]
Run `export.py` for the first time. It reports that database is empty and attempts to retrieve last 560 days' worth of transactions. After a while it fails with:

```
Traceback (most recent call last):
  File "./export.py", line 114, in <module>
    export()
  File "./export.py", line 90, in export
    trans = browser.get_all_transactions(b, account, last_date)
  File "/path/to/nab-export/lib/browser.py", line 255, in get_all_transactions
    b = query_server_transactions(b, start_date)
  File "/path/to/nab-export/lib/browser.py", line 234, in query_server_transactions
    b.submit()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_mechanize.py", line 541, in submit
    return self.open(self.click(*args, **kwds))
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_mechanize.py", line 230, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 344, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 332, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 1170, in https_open
    return self.do_open(conn_factory, req)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 1118, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 54] Connection reset by peer>
```

Perhaps timeout settings need to be changed.

**Comment by parxier** [comment]
Issue #1. BOOM!
